import { describe, expect, test, vi } from 'vitest'
import {
  DataValidatorSpy,
  Load{{pascalCase name}}DetailRepositorySpy,
  throwError,
} from '@test-mocks'
import { DbLoad{{pascalCase name}}Detail } from './load-{{kebabCase name}}-detail-service'
import { Load{{pascalCase name}}DetailError } from './errors'
import { {{pascalCase name}}Model } from '../{{kebabCase name}}-model'
import { Load{{pascalCase name}}DetailRepositoryProtocol } from './protocols'

type SutTypes = {
  sut: DbLoad{{pascalCase name}}Detail
  repository: Load{{pascalCase name}}DetailRepositorySpy
  validator: DataValidatorSpy<Load{{pascalCase name}}DetailRepositoryProtocol.Params>
}
const makeSut = (): SutTypes => {
  const repository = new Load{{pascalCase name}}DetailRepositorySpy()
  const validator = new DataValidatorSpy()
  const sut = new DbLoad{{pascalCase name}}Detail(repository, validator)
  return {
    sut,
    repository,
    validator,
  }
}

describe('Test Suite for load-{{kebabCase name}}-detail-service.spec', () => {
  test('Ensure that load in repository is called once and with same parameters', async () => {
    const { sut, repository } = makeSut()
    const spy = vi
      .spyOn(repository, 'loadById')
      .mockImplementation(() => Promise.resolve({} as {{pascalCase name}}Model))
    const id = '1'
    await sut.load(id)
    expect(spy).toHaveBeenCalledOnce()
    expect(spy).toHaveBeenCalledWith(id)
  })

  test('Ensure that validate in validator is called once', async () => {
    const { sut, validator } = makeSut()
    const spy = vi
      .spyOn(validator, 'validate')
      .mockImplementation(() => Promise.resolve({ success: true } as any))
    await sut.load('1')
    expect(spy).toHaveBeenCalledOnce()
  })

  test('Ensure that load {{kebabCase name}} detail service to throw a Custom Load{{pascalCase name}}DetailError when repository throws', async () => {
    const { sut, repository } = makeSut()
    vi.spyOn(repository, 'loadById').mockImplementationOnce(() =>
      throwError(new Load{{pascalCase name}}DetailError('Error')),
    )
    const promise = sut.load('1')
    await expect(promise).rejects.toThrowError(Load{{pascalCase name}}DetailError)
  })

  test('Ensure that load {{kebabCase name}} detail service returns exactly what the repository returns', async () => {
    const { sut, repository } = makeSut()
    const result = await sut.load('1')
    expect(result).toEqual(repository.result)
  })
})
